### ISSUE TITLE
FYI

### ISSUE THREAD

**Issue by clayh53** [edwardtufte/tufte-css#1]
I'm a total newbie at how pull requests are done, but anyway, thanks for doing most of the heavy lifting on the tufte-css repository. I forked your repository and added some CSS line-height and margin values so that all the sidenotes and marginnotes are on the same baseline typographic scale. I also added media queries so that the font sizes scale as the browser width changes. Anyway, if you want to add this to your original commit, please feel free. https://github.com/clayh53/tufte-css

**Comment by daveliepmann** [comment]
I think you opened a pull request to your own repository, instead of to mine...I'm not entirely sure how to rectify that! :)

I'm definitely interested in incorporating some of your changes. I think the best way to do that would be with multiple pull requests based on individual, targeted commits. For instance, one commit (and one pull request) for standardizing line-height and margins, one for media queries, and so one.

I also noticed you added an 'r' to ET Bembo...do I have the name wrong?

**Comment by clayh53** [comment]
Okay, let me see if I can walk my way through this. The main things I mucked around with were the typographic scale related stuff plus added some media queries so that the line lengths stay sane when the browser resizes.

As far as the ETBrembo goes - that is a typo that crept in during my editing. I have fixed it now!
