### ISSUE TITLE
Tag releases and semantic versioning

### ISSUE THREAD

**Issue by dakrone** [edwardtufte/tufte-css#103]
Hi and thanks for Tufte CSS!

Would it be possible to tag releases by using git tags and perhaps use semantic versioning with the project?

I'm working on a project that is compatible with tufte-css but doesn't include it as a dependency (https://github.com/dakrone/ox-tufte). While I will follow development as well as I can, there are some cases where changes like https://github.com/edwardtufte/tufte-css/commit/006939cb4d4f5cf9bf967e876d0eb02dd782a2eb (from #102) will break any website using my project since it will continue to generate code with `<pre class="code"></pre>` blocks, since the old style for `.code` was removed, this means code blocks will not have the correct style applied.

I'd love to be able to say my project is compatible with version X.X.X of tufte-css and have users be able to download a release or checkout a git tag that will be compatible. Until then I will try to track the `gh-pages` branch as closely as possible in my project.

**Comment by daveliepmann** [comment]
Excellent idea. Apologies for the breaking changes. I'll try to get to this soon.

**Comment by daveliepmann** [comment]
I went back and added [tags for the major releases](https://github.com/edwardtufte/tufte-css/tags) as I see them. Your work was probably based on [1.0](https://github.com/edwardtufte/tufte-css/releases/tag/v1.0) or something close to it, since that's been the public release for some months. 

Thanks for the push on this. Releases have been something I knew was necessary for a while but just hadn't gotten cleaned up my process to deliver.

**Comment by dakrone** [comment]
Thanks for doing this!
