### ISSUE TITLE
figcaption pulled to right margin for wide browser window

### ISSUE THREAD

**Issue by mbucc** [edwardtufte/tufte-css#108]
With the following HTML,

```
        <figure>
          <img src="img/tomato.png" class="webfeedsFeaturedVisual"/>
          <figcaption>Test caption (inside).</figcaption>
        </figure>
```

If I make the browser wide enough, the caption moves from right justified with the image to right justified with the full width.

The following patch fixes this behavior.

```
--- tufte.css
+++ /dev/null
@@ -125,7 +125,6 @@ figure { padding: 0;

 figcaption { float: right;
              clear: right;
-             margin-right: -48%;
              margin-top: 0;
              margin-bottom: 0;
              font-size: 1.1rem;
```

**Comment by daveliepmann** [comment]
Thanks for opening this. See also #44.

**Comment by daveliepmann** [comment]
Resolved by applying above patch in e6ec954. 

I'd like to see `figcaption` examples added back to the demo document. Until then I'll leave this issue open.

**Comment by dkasak** [comment]
I'm not sure I understand this change. I was under the impression that the intended effect *was* that the `figcaption` is displayed in the margin (as it is done for the first figure [here](https://edwardtufte.github.io/tufte-css/#figures)), but that it couldn't be made to work to behave exactly like a margin note. That's why the example I just linked uses `<span class="marginnote">` instead.

Yet this change seems to have the opposite intention: to align the `figcaption` beneath and to the right of the figure instead of it being in the margin.

Am I misunderstanding something?

**Comment by daveliepmann** [comment]
What you call the intended effect was the original goal of figcaptions. My experience with #44 was to see that as a fool's errand, and to use `figcaption` for your "opposite intention", which correctly identifies the goal as putting the caption beneath the figure, right-aligned.

**Comment by dkasak** [comment]
Oh. I have in fact read #44, but missed that it was closed.

Is the official recommendation then to use a margin note inside a `figure` to serve the purpose of annotating an image (which is not otherwise introduced in the text)? Because the results I'm getting from using `figcaption` look quite bad, IMO.

**Comment by daveliepmann** [comment]
>Is the official recommendation then to use a margin note inside a figure to serve the purpose of annotating an image (which is not otherwise introduced in the text)? 

I wouldn't say there's an official position on the subject. However margin notes do seem like a reasonable tool to start with for that purpose.

>Because the results I'm getting from using figcaption look quite bad, IMO.

The project rationale says:

>[Tufte CSS] should be a starting point, not a design goal, because any project should present their information as best suits their particular circumstances.

It sounds like you need to address your particular circumstances with custom CSS.

**Comment by dkasak** [comment]
Got it, thanks!

**Comment by daveliepmann** [comment]
I think this has been resolved by application of the patch, so closing this now.
