### ISSUE TITLE
Refactor CSS to be mobile first

### ISSUE THREAD

**Issue by fulldecent** [edwardtufte/tufte-css#159]
Currently, CSS is factored to have the base case be desktops (i.e. mobile code is inside `@media (max-width: 760px)`).

However nowadays mobile traffic is the majority. So best practice is that the CSS be written smaller viewports first and then use more specificity for larger viewports (e.g. `@media (min-width: 760px)`).

**Comment by daveliepmann** [comment]
My work the last few years has been largely back-end, so I'm not familiar with that best practice. It sounds reasonable, but I'd like to see some sources. Regardless, I refer you (again) to [Project Scope and Status](https://github.com/edwardtufte/tufte-css#project-scope-and-status) from the README:

>This project is maintained but not under active development. It is considered essentially feature-complete. Refactoring and new functionality are a very low priority. However, contributions are still welcome to fix bugs or add functionality.

I'm not going to spend the (substantial) time necessary to refactor `tufte.css` to fulfill a best-practices checkbox. The project works as-is and I don't plan to spend a lot of time on it unless funding is made available. If you're interested in providing funding, please contact me by email.

If *you* did the work and submitted a PR, I'd review it positively and it might get merged. But I'd need to see fairly comprehensive evidence showing that such a substantial change preserved functionality on a variety of devices and documents before moving forward, though. So that's a major prerequisite. Until then I'm going to close this.

**Comment by fulldecent** [comment]
*FYI, I'm opening issues here to document initiatives for things I am implementing that may possibly be in project scope. I'm just deciding for myself which things to contribute upstream or which to keep for myself.*
