### ISSUE TITLE
No styling for table elements anymore?

### ISSUE THREAD

**Issue by trosel** [edwardtufte/tufte-css#160]
> [When brash, young Tufte CSS handled tables](https://github.com/edwardtufte/tufte-css/tree/94ac0dfc49729269523b9234c853b27f5458d6f2), our solution for situations such as this was Trebuchet. I think that would suit your case well.

_Originally posted by @daveliepmann in https://github.com/edwardtufte/tufte-css/issues/97#issuecomment-244115343_

Does Tufte no longer include _any_ styling for table elements? If not, can you recommend an alternative?

**Comment by daveliepmann** [comment]
You’re right, Tufte CSS now basically abstains from tables entirely. After
some experimentation we realized that the task required more nuance than
fit within this project’s constraints.

One particular challenge with tables that I think more people should
meditate on is that our source material very clearly advises us to design
tables as best suits a particular use case. So providing just a single set
of table styles would have been insufficient. We are left to start from
first principles in each instance.

I can’t recommend a particular alternative, because I haven’t worked on
this kind of thing for years. These days I either take the commodified
table styles that some library provides, or a designer on my team creates a
custom solution. Sorry.

trosel <notifications@github.com> schrieb am Mo. 7. Sept. 2020 um 18:55:
