### ISSUE TITLE
tufte.css and tufte.min.css have different update dates

### ISSUE THREAD

**Issue by mireille-raad** [edwardtufte/tufte-css#166]
Hey!

I noticed that:
- `tufte.css` was updated 13 months ago
- `tufte.min.css` was updated 2 years

<img width="918" alt="Screen Shot 2021-07-28 at 9 42 21 AM" src="https://user-images.githubusercontent.com/521705/127332638-d54e11bd-5797-4c04-af9b-15a810c360ca.png">

There is probably a way to make this automatic by using GitHub Actions... the idea is that when the `.css` file is updated, the `.min.css` is automatically generated.... is this something you would be interested in doing? I can also submit a Pull Request if you would merge it.

**Comment by daveliepmann** [comment]
I think the mismatch might've been because I hadn't released a new version despite some changes. That should be fixed now that I released [1.8.0](https://github.com/edwardtufte/tufte-css/releases/tag/v1.8.0). I think the [manual process](https://github.com/edwardtufte/tufte-css#deploying) is fine for our needs but if there's a simple setting we could try it. Thanks for pinging me on this, it's good to be reminded.
