### ISSUE TITLE
mix-blend-mode for some images

### ISSUE THREAD

**Issue by daveliepmann** [edwardtufte/tufte-css#23]
[Raised by Jonathon Bellew](https://twitter.com/jonathonbellew/status/629181264709484544):

> if you wanted to remove the harsh white background in images, mix-blend-mode: multiply would work :)

The images in the demo doc need this to blend their pure-white background with the page's `#fffff8` background. But is it necessary for the project? Is this a general concern?

**Comment by crmackay** [comment]
I had this cause problems when I was adding an off-canvas menu to my blog (on mobile the menu slides out and over the article). With `mix-blend-mode`, the figures were "mixed" with the overlaying `div`, instead of being covered-up as desired.

So, I think this is likely to get in the way of many downstream uses of `tufte-css` which could include overlays, modals, etc. I think if you want the background of your figures to match the page background, you should just re-make your figures with the appropriate background color (which is given on the demo/instruction page) .

`mix-blend-mode: multiply` can also have unforeseen consequences on certain aspects of figures, like the effects on the type and gridlines seen here:

![mix-blend-mode](https://cloud.githubusercontent.com/assets/3801862/10108088/f4d8671c-638c-11e5-8542-44f21a65341d.gif)

**Comment by daveliepmann** [comment]
`mix-blend-mode` no longer needed for new image examples. Thanks for the heads-up and explanation, @crmackay 

Resolved by b9a2204fcc03ae3e686e70f0983b9bb432481a59
