### ISSUE TITLE
Can you add a page break tag?

### ISSUE THREAD

**Issue by neuwirthe** [edwardtufte/tufte-css#30]
I would like to force pagebreaks when I print a web page with this style.
I tried a few suggestions, e.g.
http://www.htmlgoodies.com/beyond/css/article.php/3470341/CSS-and-Printing.htm

But I could not make any of these work.
Could you consider adding such a style tag?

**Comment by ghost** [comment]
Have you tried https://stackoverflow.com/a/21270036

**Comment by neuwirthe** [comment]
This does not work as it should.
This might be related to the dynamically defined font sizes.

**Comment by ghost** [comment]
Works great for me. I just tested it.

**Comment by ghost** [comment]
Here is a gist to demonstrate how to do it: https://gist.github.com/xHN35RQ/c9cd616acc4b9bfb93ac

**Comment by daveliepmann** [comment]
Thanks for that gist, @xHN35RQ. 

I'd like to add this functionality to `tufte.css`, and an example to `index.html`, but for me to feel OK doing so we'd need to also fix some other considerations for print. For instance, revert to pure black for text and pure white for the background. I'm tagging this help-wanted for anyone who wants to do that work; I don't have the desire to do the necessary testing right now.

**Comment by ghost** [comment]
I don't see any reason to add this. If you want to print to physical printer or to PDF, then you're much better off using [pandoc's Tufte template](https://github.com/wcaleb/pandoc-templates/blob/master/handout.tex) and writing your content in Latex, Markdown, or any other input that pandoc accepts. `tufte.css` should probably remain a web centric project. Otherwise you're re-inventing the wheel.

Here's an example of using Pandoc to convert from Multi-Markdown to PDF using Tufte Latex to create Tufte styled PDF's - http://plaintextadventure.com/blog/instant-pdfs-via-right-click.html

Much better option than printing HTML/CSS from web browser.

**Comment by daveliepmann** [comment]
All excellent points.

**Comment by ghost** [comment]
:+1:

**Comment by neuwirthe** [comment]
It turns out the problem was with Safari. Somehow, Safari does not get the correct information about the page size of the printer. Things work nicely with Firefox.
