### ISSUE TITLE
Missing rules around booktabs-style table

### ISSUE THREAD

**Issue by godbyk** [edwardtufte/tufte-css#60]
There should be heavy rules at the top and bottom of the booktabs-style table.

**Comment by daveliepmann** [comment]
From `index.html`, with emphasis added here:

> As an example of alternative table styles, academic publications written in LATEX often rely on the booktabs package to produce clean, clear tables. Similar results, **tweaked to Tufte’s preference for minimal extraneous lines**, can be achieved in Tufte CSS with the booktabs class.

Orthodox booktabs, which Tufte CSS adopted for a time, has heavy top and bottom rules. Edward Tufte requested they be removed so the table better reflects his idea of data-ink ratio maximization. Since this is after all Tufte CSS and not booktabs CSS, I feel that it is reasonable to modify orthodox booktabs styling. So while you're correct that booktabs as usually seen have heavy rules at top and bottom, this is not something that booktabs-in-Tufte-CSS will reflect.

**Comment by godbyk** [comment]
Fair enough. In that case, though, I'd suggest removing the booktabs style entirely as there's too little to differentiate it from the base Tufte style.

**Comment by daveliepmann** [comment]
You're right. A slate of changes to Tufte CSS tables are on an internal to-do list, and removing booktabs may end up being part of that. I would definitely however like to see orthodox booktabs CSS to live on in a separate gist or repo, if anyone wants to make that happen.
