### ISSUE TITLE
Need favicon

### ISSUE THREAD

**Issue by daveliepmann** [edwardtufte/tufte-css#76]
We have no favicon. Ideas?

**Comment by crmackay** [comment]
just an idea:

a sparkline could be cool...it would be even cooler if it was based on real data somehow...

example: 
![](http://www.xiconeditor.com/ImageFromStorage.ashx?Name=50c1f216-8d4e-42be-af89-a6eb905c28d4_16.png)

**Comment by barneycarroll** [comment]
Isn't something which has the superficial appearance of representing something but has no actual purpose the antithesis of Tufte's life work?

**Comment by crmackay** [comment]
@barneycarroll sure...which is why I was thinking you could make it represent something....

the favicon could be pulled from a server, which generates and serves up an up-to-date sparkline `.png` file based on ...something...I can't think of a good example...

In general, this would be a cool way for a website to display a single trend, not unlike the clock icon on the iPhone home screen displaying the current time, or the calendar icon displaying the current date.

For this to work, though I think one would need to somehow signal to the browser that the file has changed. I'm not sure what the best technique would be for that.

It's a convoluted, but interesting idea.

**Comment by jdbann** [comment]
How about an approximation of the layout this package provides?

![tufte-css-favicon](https://cloud.githubusercontent.com/assets/1191840/16118798/9ceb1bc0-33d0-11e6-82ca-2597a1244d38.png)

**Comment by adamschwartz** [comment]
One option is the “ET” mark used as the avatar image for https://github.com/edwardtufte.

<img width="32" src="https://cloud.githubusercontent.com/assets/154613/16136233/d8823bfc-33f6-11e6-8a82-5f372cb8caa2.png">

However, https://www.edwardtufte.com does not appear to use a favicon so that may be the answer right there.

**Comment by daveliepmann** [comment]
I think @adamschwartz has the correct here. Closing this for lack of need.
