### ISSUE TITLE
Inline code text is too big on iPhone 6 landscape

### ISSUE THREAD

**Issue by daveliepmann** [edwardtufte/tufte-css#81]
When viewing the demo document on an iPhone 6 in landscape mode, inline `code` text is oversized relative to body text. 

Example pending.

Fixes for this must not disturb other resolutions.

**Comment by daveliepmann** [comment]
Issue experienced in Chrome; verify across Safari as well.

**Comment by daveliepmann** [comment]
Curiously, it does not appear to show up when imitating iPhone 6 with Chrome developer tools.

**Comment by crmackay** [comment]
this is weird. I get it too on Safari on my iPhone 6 (iOS 9.2.1)

It seems like it is scaling the `code` font size based on the window width...but I don't see why it would be doing that (especially just for the code elements). Might have to hook up an iPhone to a mac and use safari web inspector to get to the bottom of this one.

**Comment by tkraak** [comment]
Confirmed on iPhone 6 Plus (iOS 9.2.1) as well. Strange.

I'm hoping to hook my phone up tonight.

**Comment by ckweb** [comment]
I found a clue for a solution to this problem here:
https://www.sitepoint.com/community/t/iphone-landscape-view-blows-up-font-sizes/30010

Applying this rule fixed the problem in my iPhone simulator:
code {
    -webkit-text-size-adjust: none;
}

But you'll want to limit that with a media query for small screens. And there are dangers related to disabling user zoom with this setting. 
More info here: https://developer.mozilla.org/en-US/docs/Web/CSS/text-size-adjust

**Comment by opattison** [comment]
You can do better by setting `-webkit-text-size-adjust: 100%` (`100%` instead of `none`). No risks with zooming behavior this way.

Don’t take my word for it: https://github.com/necolas/normalize.css/blob/master/normalize.css#L9-L18

**Comment by daveliepmann** [comment]
Implemented @opattison's solution in c330c2a. Appears to fix things. Many thanks to all who chimed in to kill this beast. Apologies for the delay.
